default:
  image: ubuntu:20.04

ci:
  stage: build
  before_script:
    - apt-get update && apt-get -y install curl
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt-get update && apt-get -y install packer
    - packer --version
  script:
    - cd vagrant-ubuntu
    - packer validate .
