default:
  image: ubuntu:20.04

ci:
  stage: build
  before_script:
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - sudo apt-get update && sudo apt-get install packer
    - packer --version
  script:
    - cd vagrant-ubuntu
    - packer validate .
