Vagrant.configure("2") do |config|
  # config.ssh.insert_key = true
	config.vm.provider :virtualbox do |v|
		# v.customize ["modifyvm", :id, "--memory", 1024]
		# v.customize ["modifyvm", :id, "--cpus", 2]
		# v.customize ["modifyvm", :id, "--cpuexecutioncap", 50]
    # https://github.com/joelhandwell/ubuntu_vagrant_boxes/blob/master/u16/Vagrantfile#L11
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
	end
end
